services:
  - type: web
    name: jdr-tables
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
